language: java
install: true

jdk:
  - oraclejdk8

services:
  - docker

script:
  - ./gradlew build --scan -s
  - docker build -t $DOCKER_UN/devtools-svc .
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_UN" --password-stdin
  - docker push $DOCKER_UN/devtools-svc
